<template>
      <div id="toc" class="float-toc">
      <div class="toc-content">
        <div class="toc-top-border"></div>
        <p class="toc-title">{{this.object.title}}</p>
        <div class="toc-close" @click="closeContent()">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="12"  xml:space="preserve" id="canvas1" style="margin-left: 42px;margin-top: 57px;transform: scale(1.1) rotate(-48deg);">
              <!-- Generated by PaintCode (www.paintcodeapp.com) -->
              <path id="canvas1-bezier" stroke="none" fill="rgb(255, 255, 2555)" d="M 8.31,6 L 12.63,10.02 C 13.12,10.48 13.12,11.19 12.63,11.65 12.4,11.86 12.06,12 11.76,12 11.45,12 11.11,11.86 10.89,11.65 L 6.56,7.62 2.24,11.65 C 2.01,11.86 1.67,12 1.37,12 1.06,12 0.72,11.86 0.49,11.65 0,11.19 0,10.48 0.49,10.02 L 4.82,6 0.49,1.97 C 0,1.51 0,0.8 0.49,0.34 0.99,-0.11 1.75,-0.11 2.24,0.34 L 6.56,4.37 10.89,0.34 C 11.38,-0.11 12.14,-0.11 12.63,0.34 13.12,0.8 13.12,1.51 12.63,1.97 L 8.31,6 Z M 8.31,6" />
          </svg>


        </div>
        <ul id="v-for-object" class="TableOfContents">
            <li  v-for="(value, key) in this.object.list">
            <p><a href="javascript:void(0)" @click="goRootAnchor(value)">{{ key }}</a></p>
            </li>
        </ul>
      </div>
      <div class="toc-icon"  @click="expandContent">
        <svg class="toc-svg" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="23"  xml:space="preserve" id="canvas1">
            <!-- Generated by PaintCode (www.paintcodeapp.com) -->
            <path class="toc-path" id="canvas1-bezier" stroke="none" fill="rgb(0, 0, 53)" d="M 1.5,3 C 0.67,3 0,2.33 0,1.5 0,0.67 0.67,-0 1.5,-0 2.33,-0 3,0.67 3,1.5 3,2.33 2.33,3 1.5,3 Z M 9.5,-0 L 28.5,-0 C 29.33,-0 30,0.67 30,1.5 L 30,1.5 C 30,2.33 29.33,3 28.5,3 L 9.5,3 C 8.67,3 8,2.33 8,1.5 L 8,1.5 8,1.5 C 8,0.67 8.67,-0 9.5,-0 Z M 1.5,13 C 0.67,13 0,12.33 0,11.5 0,10.67 0.67,10 1.5,10 2.33,10 3,10.67 3,11.5 3,12.33 2.33,13 1.5,13 Z M 9.5,10 L 28.5,10 C 29.33,10 30,10.67 30,11.5 30,12.33 29.33,13 28.5,13 L 9.5,13 C 8.67,13 8,12.33 8,11.5 8,10.67 8.67,10 9.5,10 Z M 1.5,23 C 0.67,23 0,22.33 0,21.5 0,20.67 0.67,20 1.5,20 2.33,20 3,20.67 3,21.5 3,22.33 2.33,23 1.5,23 Z M 9.5,20 L 28.5,20 C 29.33,20 30,20.67 30,21.5 30,22.33 29.33,23 28.5,23 L 9.5,23 C 8.67,23 8,22.33 8,21.5 8,20.67 8.67,20 9.5,20 Z M 9.5,20" />
        </svg>
      </div>
      </div>
</template>

<script>

  var isOpen = false;
  export default {
    name: 'toc',
    props:['tocData'],
    data: function () {return {
        object: this.tocData
      }
    },
    methods: {
      goRootAnchor: function(selector){
        this.$root.goAnchor(selector)
      },
      expandContent:function(){
        if(isOpen == false){

          this.$el.classList.remove("float-toc-hover");

          isOpen = !isOpen;
          this.$el.querySelector('.toc-icon').classList.add("toc-icon-hide");
          this.$el.classList.add("float-toc-show");
          this.$el.querySelector('.toc-content').classList.add("toc-content-show");
          this.$el.querySelector('.toc-close').classList.add("toc-close-show");
        }
        
      },
      closeContent:function(){
        if(isOpen == true){

          
          setTimeout(function(){
            isOpen = !isOpen;
          }, 500);
          this.$el.classList.remove("float-toc-show");
          this.$el.querySelector('.toc-icon').classList.remove("toc-icon-hide");
          this.$el.querySelector('.toc-content').classList.remove("toc-content-show");
          this.$el.querySelector('.toc-close').classList.remove("toc-close-show");
        }
      },

    },
    mounted:function(){

      // var objValue = Object.values(this.object.list);
      // var objKey = Object.keys(this.object.list);
      // console.log(objKey)


      isOpen=false;
     
      this.$el.addEventListener("mouseover", function() {
        if(!isOpen){
          this.classList.add("float-toc-hover");
        }
      });

      this.$el.addEventListener("mouseout", function() {
        if(!isOpen){
          this.classList.remove("float-toc-hover");
        }
      });

    },
    destroyed:function(){

    }
  }

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>


/* fix this transition && add close button */
.float-toc{
    box-shadow: 0 4px 16px 0 rgba(0,0,0,0.08), 0 1px 4px 0 rgba(0,0,0,0.12);
    border-radius: 3px;
    display: inline-block;
    position: fixed;
    left: 40px;
    bottom: 40px;
    background: #888;
    border:1px solid #888;
    overflow: hidden;
    z-index: 1;

    padding-left: 0px;
    padding-right: 0px;
    min-width: 40px;
    max-width: 40px;
    max-height: 40px;

    -webkit-box-shadow: 0 4px 20px rgba(0,0,0,0.22);
    box-shadow: 0 4px 20px rgba(0,0,0,0.22);

    /* -webkit-transition: padding-left 0.6s ease,padding-right 0.6s ease,max-width 0.6s ease,min-width 0.6s ease,max-height 0.6s ease,background-color 0.3s ease, border 0.3s ease,box-shadow 0.3s ease,transform 0.3s ease; */
    -webkit-transition: padding-left 0.4s ease-out,padding-right 0.4s ease-out,max-width 0.4s ease-out,min-width 0.4s ease-out,max-height 0.4s ease,background-color 0.3s ease, border 0.3s ease,box-shadow 0.3s ease,transform 0.3s ease;
    transition: padding-left 0.4s ease-out,padding-right 0.4s ease-out,max-width 0.4s ease-out,min-width 0.4s ease-out,max-height 0.4s ease,background-color 0.3s ease, border 0.3s ease,box-shadow 0.3s ease,transform 0.3s ease;


}

.float-toc-show{
    -webkit-transition: padding-left 0.4s ease,padding-right 0.4s ease,max-width 0.4s ease,min-width 0.4s ease,max-height 0.8s 0.15s ease,background-color 0.3s ease, border 0.3s ease,box-shadow 0.3s ease,transform 0.3s ease;
    transition: padding-left 0.4s ease,padding-right 0.4s ease,max-width 0.4s ease,min-width 0.4s ease,max-height 0.8s 0.15s ease,background-color 0.3s ease, border 0.3s ease,box-shadow 0.3s ease,transform 0.3s ease;
/* 
    transition: all 0.6s ease; */
    background:white;
    border:0px solid rgba(0,0,0,0);
    padding-left: 20px;
    padding-right: 20px;
    min-width: 140px;
    max-width: 400px;
    max-height: 600px;
}


.toc-top-border {
    width: 100%;
    background: #f1f1f1;
    height: 1px;
    top: 50px;
    position: relative;
}


.toc-title{
    text-align: left;
    margin-left: 1px;
    font-weight: 500;
    /* font-family: "Avenir", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", Helvetica, Arial, sans-serif; */
}


.float-toc ul{
    padding-left: 24px;
}

.float-toc li {
    counter-increment: li;
    list-style-type:none;
}

.float-toc li p {
    margin: 0px;
    margin-top: 8px;
}

.float-toc li a {
    font-size: 12px;
    color:#333;
}


.float-toc li::before {
  content: counter(li, decimal-leading-zero);
  color:#333;
  display: inline-block; 
  width: 1em;
  margin-left: -1.3rem;
  position: absolute;
  text-align: right; 
  direction: rtl;
  font-size: 10px;
  margin-top: 3px;
  /* font-family: "Avenir", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", Helvetica, Arial, sans-serif; */
}

.toc-content{
  visibility: hidden;
  opacity: 0;
  -webkit-transition:all 0.2s 0.05s ease;
  transition:all 0.2s 0.05s ease;
  transform: translateY(30px)
}

.toc-close{
    display: inline-block;
    position: absolute;

    right: -100px;
    cursor: pointer;
    top: -38px;
    /* transform: scale(0.5) rotate(48deg) translateX(-75px) translateY(-75px); */
    transform: scale(0.5) rotate(48deg) translateX(-90px) translateY(-90px);
    opacity: 1;
    width: 100px;
    height: 80px;
    background: #888;
    background-repeat: no-repeat;
    transition:all 0.2s ease;
}

.toc-close-show{
   right: -70px;
   transform: scale(0.5) rotate(48deg) translateX(0px) translateY(0px);
   transition:all 0.5s 0.2s ease;
}

.toc-content-show{
  visibility: visible;
  opacity: 1;
  -webkit-transition:all 0.3s 0.3s ease;
  transition:all 0.3s 0.3s ease;
  transform: translateY(0px)
}

.toc-icon{
  /* top: 13px;
  left: 10px; */
  display: inline-block;
  position: absolute;
  cursor: pointer;
  bottom: 0px;
  width: 100%;
  height: 40px;
  visibility: visible;
  opacity: 1;
  transform: translateY(0px);
  -webkit-transition:transform 0.3s 0.3s ease,opacity 0.3s 0.3s ease,visibility 0s 0.3s ease;
  transition:transform 0.3s 0.3s ease,opacity 0.3s 0.3s ease,visibility 0s 0.3s ease;
}

.toc-icon-hide{
  transform: translateY(60px);
  -webkit-transition:transform 0.3s ease,opacity 0.3s ease,visibility 0s 0.45s ease;
  transition:transform 0.3s ease,opacity 0.3s ease,visibility 0s 0.45s ease;
  visibility: hidden;
  opacity: 0;
}

.float-toc-hover {
  background: white;
  border: 1px solid rgba(0,0,0,0);
  -webkit-box-shadow: 0 6px 20px rgba(0,0,0,0.15);
  box-shadow: 0 6px 20px rgba(0,0,0,0.15);
  -webkit-transform: scale(1.1);
  transform: scale(1.1);
}

.float-toc:hover .toc-path {
  fill:#888;
}

.toc-svg{
    display: inline-block;
    position: relative;
    left: 10px;
    top: 13px;
}

.toc-path{
  /* fill:white; */
  fill:white;
  transition:all 0.3s;
  transform: scale(0.6);
}


</style>
